"""slug column fixing

Revision ID: 3998aeb886df
Revises: 557f7b82d10c
Create Date: 2024-08-23 01:01:01.869986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3998aeb886df'
down_revision = '557f7b82d10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('uq_slug', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_slug', ['slug'])

    # ### end Alembic commands ###
