"""slug column to Post model added

Revision ID: 557f7b82d10c
Revises: 4c9efa91465c
Create Date: 2024-08-23 00:34:38.726238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557f7b82d10c'
down_revision = '4c9efa91465c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint('uq_slug', ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('uq_slug', type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
