"""Add videos links to Post model

Revision ID: bf06b5ec0e16
Revises: e02e200b3d83
Create Date: 2024-08-23 14:38:09.308913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf06b5ec0e16'
down_revision = 'e02e200b3d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_links', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('video_links')

    # ### end Alembic commands ###
