"""slug column unique=True

Revision ID: e02e200b3d83
Revises: 3998aeb886df
Create Date: 2024-08-23 01:10:28.026951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02e200b3d83'
down_revision = '3998aeb886df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_slug', ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('uq_slug', type_='unique')

    # ### end Alembic commands ###
